# Generated by Django 4.2.1 on 2023-06-14 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaignfinance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='election',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='government_entity',
        ),
        migrations.AddField(
            model_name='campaign',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_campaigns', to='campaignfinance.election'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_transactions', to='campaignfinance.campaign'),
        ),
    ]
