# Generated by Django 4.2.1 on 2023-06-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignfinance', '0002_remove_election_campaigns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='government_entity',
        ),
        migrations.RemoveField(
            model_name='document',
            name='government_entity',
        ),
    ]
