# Generated by Django 4.2.1 on 2023-06-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignfinance', '0003_remove_campaign_government_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='campaign',
        ),
    ]
